# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: drsounds.Swimfit
PackageVersion: 1.0.0
InstallerType: portable
Commands:
- swimfit
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/drsounds/swimfit/releases/download/swimfit-main-13b3802d710e9f0418797bc609a963a219cfefc8/swimfit.exe
  InstallerSha256: A8C0F07B1ABB959001D56B07DB1807EB16B11676BFBB50E208DF180A46FA8A8A
ManifestType: installer
ManifestVersion: 1.12.0
